exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex("tasting_notes")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("tasting_notes").insert([
        { tasting_note: "Floral" },
        { tasting_note: "Lemongrass" },
        { tasting_note: "Orange Blossom" },
        { tasting_note: "Jasmine Honeysuckle" },
        { tasting_note: "Magnolia" },
        { tasting_note: "Lavender" },
        { tasting_note: "Rose Hips" },
        { tasting_note: "Hibiscus" },
        { tasting_note: "Vegetal" },
        { tasting_note: "Earthy" },
        { tasting_note: "Herb" },
        { tasting_note: "Bergamot" },
        { tasting_note: "Hops" },
        { tasting_note: "Black Tea" },
        { tasting_note: "Green Tea" },
        { tasting_note: "Mint" },
        { tasting_note: "Sage" },
        { tasting_note: "Dill" },
        { tasting_note: "Grassy" },
        { tasting_note: "Snow Pea" },
        { tasting_note: "Sweet Pea" },
        { tasting_note: "Mushroom" },
        { tasting_note: "Squash" },
        { tasting_note: "Green Pepper" },
        { tasting_note: "Olive" },
        { tasting_note: "Leafy Greens" },
        { tasting_note: "Hay / Straw" },
        { tasting_note: "Tobacco" },
        { tasting_note: "Cedar" },
        { tasting_note: "Fresh Wood" },
        { tasting_note: "Soil" },
        { tasting_note: "Savory" },
        { tasting_note: "Tomato" },
        { tasting_note: "Sundried Tomato" },
        { tasting_note: "Soy Sauce" },
        { tasting_note: "Meat-Like" },
        { tasting_note: "Leathery" },
        { tasting_note: "Spice" },
        { tasting_note: "Clove" },
        { tasting_note: "Licorice Anise" },
        { tasting_note: "Curry" },
        { tasting_note: "Nutmeg" },
        { tasting_note: "Ginger" },
        { tasting_note: "Coriander" },
        { tasting_note: "Cinnamon" },
        { tasting_note: "White Pepper" },
        { tasting_note: "Black Pepper" },
        { tasting_note: "Carbon" },
        { tasting_note: "Smokey" },
        { tasting_note: "Burnt Sugar" },
        { tasting_note: "Toast" },
        { tasting_note: "Fresh Bread" },
        { tasting_note: "Grain & Cereal" },
        { tasting_note: "Barley" },
        { tasting_note: "Wheat" },
        { tasting_note: "Rye" },
        { tasting_note: "Graham Cracker" },
        { tasting_note: "Granola" },
        { tasting_note: "Sweet Bread Pastry" },
        { tasting_note: "Nut-like" },
        { tasting_note: "Almond" },
        { tasting_note: "Hazelnut" },
        { tasting_note: "Pecan" },
        { tasting_note: "Cashew" },
        { tasting_note: "Peanut" },
        { tasting_note: "Walnut" },
        { tasting_note: "Sweet" },
        { tasting_note: "Sugary" },
        { tasting_note: "Vanilla" },
        { tasting_note: "Nougat" },
        { tasting_note: "Honey" },
        { tasting_note: "Butter" },
        { tasting_note: "Cream" },
        { tasting_note: "Marshmallow" },
        { tasting_note: "Sugar Cane" },
        { tasting_note: "Brown Sugar" },
        { tasting_note: "Carmel" },
        { tasting_note: "Maple Syrup" },
        { tasting_note: "Molasses" },
        { tasting_note: "Cola" },
        { tasting_note: "Chocolate" },
        { tasting_note: "Cacao Nibs" },
        { tasting_note: "Dark Chocolate" },
        { tasting_note: "Bakers Chocolate" },
        { tasting_note: "Buttersweet Chocolate" },
        { tasting_note: "Cocoa Powder" },
        { tasting_note: "Milk Chocolate" },
        { tasting_note: "Fruit" },
        { tasting_note: "Citrus" },
        { tasting_note: "Lemon & Lemeonade" },
        { tasting_note: "Lime" },
        { tasting_note: "Grapefruit" },
        { tasting_note: "Clementine" },
        { tasting_note: "Tangerine" },
        { tasting_note: "Mandarin Orange" },
        { tasting_note: "Orange" },
        { tasting_note: "Green Apple" },
        { tasting_note: "Red Apple" },
        { tasting_note: "Watermelon" },
        { tasting_note: "Honeydew" },
        { tasting_note: "Cantaloupe" },
        { tasting_note: "White Grape" },
        { tasting_note: "Wine" },
        { tasting_note: "Green Grape" },
        { tasting_note: "Red Grape" },
        { tasting_note: "Concord Grape" },
        { tasting_note: "Apple" },
        { tasting_note: "Pear" },
        { tasting_note: "Melon" },
        { tasting_note: "Grape" },
        { tasting_note: "Tropical Fruit" },
        { tasting_note: "Lychee" },
        { tasting_note: "Star Fruit" },
        { tasting_note: "Tamarino" },
        { tasting_note: "Passion Fruit" },
        { tasting_note: "Pineapple" },
        { tasting_note: "Mango" },
        { tasting_note: "Papaya" },
        { tasting_note: "Kiwi" },
        { tasting_note: "Banana" },
        { tasting_note: "Coconut" },
        { tasting_note: "Stone Fruit" },
        { tasting_note: "Peach" },
        { tasting_note: "Nectarine" },
        { tasting_note: "Apricot" },
        { tasting_note: "Plum" },
        { tasting_note: "Cherry" },
        { tasting_note: "Black Cherry" },
        { tasting_note: "Berry" },
        { tasting_note: "Cranberry" },
        { tasting_note: "Raspberry" },
        { tasting_note: "Strawberry" },
        { tasting_note: "Blueberry" },
        { tasting_note: "Red Currant" },
        { tasting_note: "Black Currant" },
        { tasting_note: "Dried Fruit" },
        { tasting_note: "Golden Raisin" },
        { tasting_note: "Raisin" },
        { tasting_note: "Dried Fig" },
        { tasting_note: "Dried Dates" },
        { tasting_note: "Prune" }
      ]);
    });
};
