exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex("tasting_notes")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("tasting_notes").insert([
        { tasting_note: "Bitter" },
        { tasting_note: "Salt" },
        { tasting_note: "Sweet" },
        { tasting_note: "Sour" },
        { tasting_note: "Pungent" },
        { tasting_note: "Harsh" },
        { tasting_note: "Sharp" },
        { tasting_note: "Bland" },
        { tasting_note: "Mellow" },
        { tasting_note: "Acidy" },
        { tasting_note: "Winey" },
        { tasting_note: "Soury" },
        { tasting_note: "Creosol" },
        { tasting_note: "Phenolic" },
        { tasting_note: "Caustic" },
        { tasting_note: "Alkaline" },
        { tasting_note: "Astringent" },
        { tasting_note: "Rough" },
        { tasting_note: "Neutral" },
        { tasting_note: "Soft" },
        { tasting_note: "Delicate" },
        { tasting_note: "Mild" },
        { tasting_note: "Nippy" },
        { tasting_note: "Piquant" },
        { tasting_note: "Tangy" },
        { tasting_note: "Tart" },
        { tasting_note: "Hard" },
        { tasting_note: "Acrid" },
        { tasting_note: "Enzymatic" },
        { tasting_note: "Sugar Browning" },
        { tasting_note: "Dry Distilation" },
        { tasting_note: "Flowery" },
        { tasting_note: "Fruity" },
        { tasting_note: "Herby" },
        { tasting_note: "Nutty" },
        { tasting_note: "Carmelly" },
        { tasting_note: "Chocolaty" },
        { tasting_note: "Resinous" },
        { tasting_note: "Spicy" },
        { tasting_note: "Carbony" },
        { tasting_note: "Floral" },
        { tasting_note: "Fragrant" },
        { tasting_note: "Citrus" },
        { tasting_note: "Berry-like" },
        { tasting_note: "Alliceous" },
        { tasting_note: "Leguminous" },
        { tasting_note: "Nut-like" },
        { tasting_note: "Malt-like" },
        { tasting_note: "Candy-like" },
        { tasting_note: "Syrup-like" },
        { tasting_note: "Chocolate-like" },
        { tasting_note: "Vinilla-like" },
        { tasting_note: "Turpeny" },
        { tasting_note: "Medicinal" },
        { tasting_note: "Warming" },
        { tasting_note: "Pungent" },
        { tasting_note: "Smokey" },
        { tasting_note: "Ashy" },
        { tasting_note: "Coffee Blossom" },
        { tasting_note: "Tea Rose" },
        { tasting_note: "Cardamon Caraway" },
        { tasting_note: "Coriander Seeds" },
        { tasting_note: "Lemon" },
        { tasting_note: "Apple" },
        { tasting_note: "Apricot" },
        { tasting_note: "Blackberry" },
        { tasting_note: "Onion" },
        { tasting_note: "Garlic" },
        { tasting_note: "Cucumber" },
        { tasting_note: "Garden Peas" },
        { tasting_note: "Roasted Peanuts" },
        { tasting_note: "Walnuts" },
        { tasting_note: "Balsamic Rice" },
        { tasting_note: "Toast" },
        { tasting_note: "Toasted Haelnut" },
        { tasting_note: "Roasted Almond" },
        { tasting_note: "Honey" },
        { tasting_note: "Maple Syrup" },
        { tasting_note: "Bakers" },
        { tasting_note: "Dark Chocolate" },
        { tasting_note: "Swiss" },
        { tasting_note: "Butter" },
        { tasting_note: "Piney" },
        { tasting_note: "Black Current-like" },
        { tasting_note: "Camphoric" },
        { tasting_note: "Cineolic" },
        { tasting_note: "Cedar" },
        { tasting_note: "Pepper" },
        { tasting_note: "Clove" },
        { tasting_note: "Thyme" },
        { tasting_note: "Tarry" },
        { tasting_note: "Pipe Tobacco" },
        { tasting_note: "Burnt" },
        { tasting_note: "Charred" }
      ]);
    });
};
